services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: trial-ui
    ports:
      - '50000:8080'
    volumes:
      - ./swagger.yaml:/usr/share/nginx/html/swagger.yaml
    environment:
      API_URL: ./swagger.yaml

  # モックサーバー設定
  swagger-api:
    image: stoplight/prism:4
    container_name: 'trial-api'
    ports:
      - '50001:4010'
    command: mock -h 0.0.0.0 /usr/share/nginx/html/swagger.yaml
    volumes:
      - ./swagger.yaml:/usr/share/nginx/html/swagger.yaml
